version: '3'
services:
  app:
    build:
      context: ./construct_app      # Dockerfile保存場所
      dockerfile: Dockerfile-app    # Dockerfileファイル名
    image: n-app                  # イメージ名
    container_name: n-app         # コンテナ名
    ports:                          # ポート接続
      - 3000:3000
    volumes:                        # mount workdir
      - ../myapp:/src
    command: [sh, -c, npm install && npm start]
